apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-configmap
  namespace: postgresql
  labels:
    app: postgresql
data:
  PGDATA: /var/lib/postgresql/data/pgdata
  POSTGRES_DB: testdatabase
  POSTGRES_USER: testuser