apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-configmap
  labels:
    app: postgresql
data:
  POSTGRES_DB: testdatabase
  POSTGRES_USER: testuser
volumes:
  - name: data
    persistentVolumeClaim:
      claimName: postgresql-PersistentVolumeClaim