apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-persistentvolume
  namespace: postgresql
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data
  storageClassName: local