apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-PersistentVolumeClaim
  namespace: postgresql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local