apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-PersistentVolume
  namespace: postgresql
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/postgresql/data
  storageClassName: local