apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-persistentvolume
#  namespace: default
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /etc/prometheus
  storageClassName: local