apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-deployment
  namespace: redminesql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
        role: recreate-update
    spec:
      containers:
      - image: postgres:10.13
        name: postgresql
        ports:
        - containerPort: 5432
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: data
        envFrom:
          - configMapRef:
              name: redminesql-configmap
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: POSTGRES_PASSWORD
                name: app-secret
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: redminesql-persistentvolumeclaim
  strategy:
    type: Recreate