apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  labels:
    name: myingress
spec:
  rules:
  - host: db-portal.info
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: redmine-service
            port: 
              number: 8080
