apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-persistentvolumeclaim
  namespace: redminesql
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: local