apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-persistentvolume
  namespace: redminesql
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data1
  storageClassName: local