apiVersion: v1
kind: PersistentVolume
metadata:
  name: redminesql-persistentvolume
  namespace: redminesql
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /home/den/minikube_dir/lesson_5/data
  storageClassName: local