apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redminesql-persistentvolumeclaim
  namespace: redminesql
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: local