apiVersion: v1
kind: Service
metadata:
  name: redmine-service
  namespace: redminesql
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: redmine